---
- name: Ensuring rclone is installed
  become: true
  ansible.builtin.apt:
    name: rclone
- name: Stopping mount if it's running
  become: true
  ansible.builtin.command:
    cmd: "fusermount3 -u /home/{{ item }}/vault"
  loop: "{{rclone_personal_vault_users}}"
  ignore_errors: true
- name: Ensuring mount points exist
  become: true
  ansible.builtin.file:
    path: "/home/{{ item }}/vault"
    state: directory
    mode: "0700"
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ rclone_personal_vault_users }}"
- name: Making sure rclone_personal_vault group exists
  become: true
  ansible.builtin.group:
    name: "{{ rclone_personal_vault_group }}"
    state: present
- name: Making sure rclone_personal_vault_dir exists
  become: true
  ansible.builtin.file:
    path: "{{ rclone_personal_vault_dir }}"
    state: directory
    owner: root
    group: "{{ rclone_personal_vault_group }}"
    mode: "0770"
- name: Adding template service
  become: true
  ansible.builtin.template:
    src: rclone_personal_vault@.service.j2
    dest: /etc/systemd/system/rclone_personal_vault@.service
    mode: "0777"
- name: Make users able to share mount
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/fuse.conf
    line: "user_allow_other"
- name: Reloading services
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Starting service for users
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: rclone_personal_vault@{{ item }}.service
  loop: "{{ rclone_personal_vault_users }}"
